### ISSUE TITLE
QNX 6 guest - VCPU shutdown on boot

### ISSUE THREAD

**Issue by ensra** [intel/haxm#175] opened 2019-02-14 22:20 UTC
**Describe the Bug**

Summary: QNX 6 fails to boot on NetBSD.

**Host Environment**

* HAXM version: c072ad9b68e1d558a9fb791511468d10a1a9b319

* Host OS version: NetBSD 8.99.34

* Host OS architecture: x86\_64

* Host CPU model: Intel(R) Core(TM) i5-7200U

* Host RAM size: 8 GB 

* (Optional) Host computer model: 

**Guest Environment**

* Android Emulator or QEMU version: QEMU 3.1.0

* Guest OS version: 6.5.0

* Guest OS architecture: x86

**To Reproduce**

1. `qemu-system-x86_64 -accel hax -m 1.5G -cdrom qnx-6.5.0-x86-201007091524.iso`

**Expected Behavior**

Expectation: QNX should boot.

**Reproducibility**

100%

**Diagnostic Information**

Host crash dump: n/a

HAXM log: 

~~~
[ 35108.592366] haxm_panic: em_decode_insn() failed: vcpu_id=0, len=2, CS:IP=0x0:0x40c761, instr[0..5]=0xf3 0xa6 0x75 0x2d 0xc7 0x44
[ 35108.592366] haxm_warning: 4000 VMX_PIN_CONTROLS: 1f
[ 35108.592366] haxm_warning: 4002 VMX_PRIMARY_PROCESSOR_CONTROLS: 969861fa
[ 35108.592366] haxm_warning: 401e VMX_SECONDARY_PROCESSOR_CONTROLS: aa
[ 35108.592366] haxm_warning: 4004 VMX_EXCEPTION_BITMAP: 40000
[ 35108.592366] haxm_warning: 4006 VMX_PAGE_FAULT_ERROR_CODE_MASK: 0
[ 35108.592366] haxm_warning: 4008 VMX_PAGE_FAULT_ERROR_CODE_MATCH: 0
[ 35108.592366] haxm_warning: 400c VMX_EXIT_CONTROLS: 236fff
[ 35108.592366] haxm_warning: 400e VMX_EXIT_MSR_STORE_COUNT: 0
[ 35108.592366] haxm_warning: 4010 VMX_EXIT_MSR_LOAD_COUNT: 0
[ 35108.592366] haxm_warning: 4012 VMX_ENTRY_CONTROLS: 11ff
[ 35108.592366] haxm_warning: 4014 VMX_ENTRY_MSR_LOAD_COUNT: 0
[ 35108.592366] haxm_warning: 4016 VMX_ENTRY_INTERRUPT_INFO: c
[ 35108.592366] haxm_warning: 4018 VMX_ENTRY_EXCEPTION_ERROR_CODE: 0
[ 35108.592366] haxm_warning: 401a VMX_ENTRY_INSTRUCTION_LENGTH: 0
[ 35108.592366] haxm_warning: 401c VMX_TPR_THRESHOLD: 0
[ 35108.592366] haxm_warning: 6000 VMX_CR0_MASK: ffffffffe0000020
[ 35108.592366] haxm_warning: 6002 VMX_CR4_MASK: ffffffffffc8f860
[ 35108.592366] haxm_warning: 6004 VMX_CR0_READ_SHADOW: 11
[ 35108.592366] haxm_warning: 6006 VMX_CR4_READ_SHADOW: 0
[ 35108.592366] haxm_warning: 400a VMX_CR3_TARGET_COUNT: 0
[ 35108.592366] haxm_warning: 6008 VMX_CR3_TARGET_VAL_BASE: 0
[ 35108.592366] haxm_warning: 0000 VMX_VPID: 1
[ 35108.592366] haxm_warning: 2000 VMX_IO_BITMAP_A: 10f01e000
[ 35108.592366] haxm_warning: 2002 VMX_IO_BITMAP_B: 10f020000
[ 35108.592366] haxm_warning: 2004 VMX_MSR_BITMAP: 10f021000
[ 35108.592366] haxm_warning: 2006 VMX_EXIT_MSR_STORE_ADDRESS: 0
[ 35108.592366] haxm_warning: 2008 VMX_EXIT_MSR_LOAD_ADDRESS: 0
[ 35108.592366] haxm_warning: 200a VMX_ENTRY_MSR_LOAD_ADDRESS: 0
[ 35108.592366] haxm_warning: 2010 VMX_TSC_OFFSET: ffffa95f87d8228e
[ 35108.592366] haxm_warning: 2012 VMX_VAPIC_PAGE: 0
[ 35108.592366] haxm_warning: 2014 VMX_APIC_ACCESS_PAGE: 0
[ 35108.592366] haxm_warning: 201a VMX_EPTP: 1f37e501e
[ 35108.592366] haxm_warning: 482e VMX_PREEMPTION_TIMER: 0
[ 35108.592366] haxm_warning: 4400 VMX_INSTRUCTION_ERROR_CODE: 0
[ 35108.592366] haxm_warning: 4402 VM_EXIT_INFO_REASON: 30
[ 35108.592366] haxm_warning: 4404 VM_EXIT_INFO_INTERRUPT_INFO: 0
[ 35108.592366] haxm_warning: 4406 VM_EXIT_INFO_EXCEPTION_ERROR_CODE: 0
[ 35108.592366] haxm_warning: 4408 VM_EXIT_INFO_IDT_VECTORING: 0
[ 35108.592366] haxm_warning: 440a VM_EXIT_INFO_IDT_VECTORING_ERROR_CODE: 0
[ 35108.592366] haxm_warning: 440c VM_EXIT_INFO_INSTRUCTION_LENGTH: 2
[ 35108.592366] haxm_warning: 440e VM_EXIT_INFO_INSTRUCTION_INFO: 0
[ 35108.592366] haxm_warning: 6400 VM_EXIT_INFO_QUALIFICATION: 781
[ 35108.592366] haxm_warning: 6402 VM_EXIT_INFO_IO_ECX: ffffffff81000600
[ 35108.592366] haxm_warning: 6404 VM_EXIT_INFO_IO_ESI: f040
[ 35108.592366] haxm_warning: 6406 VM_EXIT_INFO_IO_EDI: ffffffff810011e0
[ 35108.592366] haxm_warning: 6408 VM_EXIT_INFO_IO_EIP: e829
[ 35108.592366] haxm_warning: 640a VM_EXIT_INFO_GUEST_LINEAR_ADDRESS: a0000
[ 35108.592366] haxm_warning: 2400 VM_EXIT_INFO_GUEST_PHYSICAL_ADDRESS: a0000
[ 35108.592366] haxm_warning: 6c16 HOST_RIP: ffffffff814f3b03
[ 35108.592366] haxm_warning: 6c14 HOST_RSP: ffffce80b1b93af0
[ 35108.592366] haxm_warning: 6c00 HOST_CR0: 80050033
[ 35108.592366] haxm_warning: 6c02 HOST_CR3: 14fb45000
[ 35108.592366] haxm_warning: 6c04 HOST_CR4: 3426f8
[ 35108.592366] haxm_warning: 0c02 HOST_CS_SELECTOR: 8
[ 35108.592366] haxm_warning: 0c06 HOST_DS_SELECTOR: 20
[ 35108.592366] haxm_warning: 0c00 HOST_ES_SELECTOR: 20
[ 35108.592366] haxm_warning: 0c08 HOST_FS_SELECTOR: 0
[ 35108.592366] haxm_warning: 0c0a HOST_GS_SELECTOR: 0
[ 35108.592366] haxm_warning: 0c04 HOST_SS_SELECTOR: 10
[ 35108.592366] haxm_warning: 0c0c HOST_TR_SELECTOR: a0
[ 35108.592366] haxm_warning: 6c06 HOST_FS_BASE: 72a6cf88fbf0
[ 35108.592366] haxm_warning: 6c08 HOST_GS_BASE: ffffffff81000600
[ 35108.592366] haxm_warning: 6c0a HOST_TR_BASE: ffffff0000012000
[ 35108.592366] haxm_warning: 6c0c HOST_GDTR_BASE: ffffff0000002000
[ 35108.592366] haxm_warning: 6c0e HOST_IDTR_BASE: ffffff0000000000
[ 35108.592366] haxm_warning: 4c00 HOST_SYSENTER_CS: 0
[ 35108.592366] haxm_warning: 6c10 HOST_SYSENTER_ESP: 0
[ 35108.592366] haxm_warning: 6c12 HOST_SYSENTER_EIP: 0
[ 35108.592366] haxm_warning: 681e GUEST_RIP: 40c761
[ 35108.592366] haxm_warning: 6820 GUEST_RFLAGS: 11006
[ 35108.592366] haxm_warning: 681c GUEST_RSP: 4057c0
[ 35108.592366] haxm_warning: 6800 GUEST_CR0: 31
[ 35108.592366] haxm_warning: 6802 GUEST_CR3: 0
[ 35108.592366] haxm_warning: 6804 GUEST_CR4: 2040
[ 35108.592366] haxm_warning: 0800 GUEST_ES_SELECTOR: 8
[ 35108.592366] haxm_warning: 0802 GUEST_CS_SELECTOR: 10
[ 35108.592366] haxm_warning: 0804 GUEST_SS_SELECTOR: 8
[ 35108.592366] haxm_warning: 0806 GUEST_DS_SELECTOR: 8
[ 35108.592366] haxm_warning: 0808 GUEST_FS_SELECTOR: 0
[ 35108.592366] haxm_warning: 080a GUEST_GS_SELECTOR: 0
[ 35108.592366] haxm_warning: 080c GUEST_LDTR_SELECTOR: 0
[ 35108.592366] haxm_warning: 080e GUEST_TR_SELECTOR: 0
[ 35108.592366] haxm_warning: 4814 GUEST_ES_AR: c093
[ 35108.592366] haxm_warning: 4816 GUEST_CS_AR: c09b
[ 35108.592366] haxm_warning: 4818 GUEST_SS_AR: c093
[ 35108.592366] haxm_warning: 481a GUEST_DS_AR: c093
[ 35108.592366] haxm_warning: 481c GUEST_FS_AR: 93
[ 35108.592366] haxm_warning: 481e GUEST_GS_AR: 93
[ 35108.592366] haxm_warning: 4820 GUEST_LDTR_AR: 82
[ 35108.592366] haxm_warning: 4822 GUEST_TR_AR: 8b
[ 35108.592366] haxm_warning: 6806 GUEST_ES_BASE: 0
[ 35108.592366] haxm_warning: 6808 GUEST_CS_BASE: 0
[ 35108.592366] haxm_warning: 680a GUEST_SS_BASE: 0
[ 35108.592366] haxm_warning: 680c GUEST_DS_BASE: 0
[ 35108.592366] haxm_warning: 680e GUEST_FS_BASE: 0
[ 35108.592366] haxm_warning: 6810 GUEST_GS_BASE: 0
[ 35108.592366] haxm_warning: 6812 GUEST_LDTR_BASE: 0
[ 35108.592366] haxm_warning: 6814 GUEST_TR_BASE: 0
[ 35108.592366] haxm_warning: 6816 GUEST_GDTR_BASE: 105c
[ 35108.592366] haxm_warning: 6818 GUEST_IDTR_BASE: 0
[ 35108.592366] haxm_warning: 4800 GUEST_ES_LIMIT: ffffffff
[ 35108.592366] haxm_warning: 4802 GUEST_CS_LIMIT: ffffffff
[ 35108.592366] haxm_warning: 4804 GUEST_SS_LIMIT: ffffffff
[ 35108.592366] haxm_warning: 4806 GUEST_DS_LIMIT: ffffffff
[ 35108.592366] haxm_warning: 4808 GUEST_FS_LIMIT: ffff
[ 35108.592366] haxm_warning: 480a GUEST_GS_LIMIT: ffff
[ 35108.592366] haxm_warning: 480c GUEST_LDTR_LIMIT: ffff
[ 35108.592366] haxm_warning: 480e GUEST_TR_LIMIT: ffff
[ 35108.592366] haxm_warning: 4810 GUEST_GDTR_LIMIT: 18
[ 35108.592366] haxm_warning: 4812 GUEST_IDTR_LIMIT: 3ff
[ 35108.592366] haxm_warning: 2800 GUEST_VMCS_LINK_PTR: ffffffffffffffff
[ 35108.592366] haxm_warning: 2802 GUEST_DEBUGCTL: 0
[ 35108.592366] haxm_warning: 2804 GUEST_PAT: 0
[ 35108.592366] haxm_warning: 2806 GUEST_EFER: 0
[ 35108.592366] haxm_warning: 2808 GUEST_PERF_GLOBAL_CTRL: 0
[ 35108.592366] haxm_warning: 280a GUEST_PDPTE0: 100000001
[ 35108.592366] haxm_warning: 280c GUEST_PDPTE1: 10100010001
[ 35108.592366] haxm_warning: 280e GUEST_PDPTE2: 100000001
[ 35108.592366] haxm_warning: 2810 GUEST_PDPTE3: 0
[ 35108.592366] haxm_warning: 681a GUEST_DR7: 400
[ 35108.592366] haxm_warning: 6822 GUEST_PENDING_DBE: 0
[ 35108.592366] haxm_warning: 482a GUEST_SYSENTER_CS: 0
[ 35108.592366] haxm_warning: 6824 GUEST_SYSENTER_ESP: 0
[ 35108.592366] haxm_warning: 6826 GUEST_SYSENTER_EIP: 0
[ 35108.592366] haxm_warning: 4828 GUEST_SMBASE: 0
[ 35108.592366] haxm_warning: 4824 GUEST_INTERRUPTIBILITY: 0
[ 35108.592366] haxm_warning: 4826 GUEST_ACTIVITY_STATE: 0
[ 35108.592366] haxm_error: vcpu has panicked, id:0
[ 35108.592366] haxm_error: log_host_cr4_vmxe: 0
[ 35108.592366] haxm_error: log_host_cr4 0
[ 35108.592366] haxm_error: log_vmxon_res 0
[ 35108.592366] haxm_error: log_vmxon_addr 10f022000
[ 35108.592366] haxm_error: log_vmxon_err_type1 0
[ 35108.592366] haxm_error: log_vmxon_err_type2 0
[ 35108.592366] haxm_error: log_vmxon_err_type3 0
[ 35108.592366] haxm_error: log_vmclear_err 0
[ 35108.592366] haxm_error: log_vmptrld_err 0
[ 35108.592366] haxm_error: log_vmoff_no 0
[ 35108.592366] haxm_error: log_vmxoff_res 0
[ 35108.592366] haxm_error: vcpu has panicked, id:0
[ 35108.592366] haxm_error: log_host_cr4_vmxe: 0
[ 35108.592366] haxm_error: log_host_cr4 0
[ 35108.592366] haxm_error: log_vmxon_res 0
[ 35108.592366] haxm_error: log_vmxon_addr 10f022000
[ 35108.592366] haxm_error: log_vmxon_err_type1 0
[ 35108.592366] haxm_error: log_vmxon_err_type2 0
[ 35108.592366] haxm_error: log_vmxon_err_type3 0
[ 35108.592366] haxm_error: log_vmclear_err 0
[ 35108.592366] haxm_error: log_vmptrld_err 0
[ 35108.592366] haxm_error: log_vmoff_no 0
[ 35108.592366] haxm_error: log_vmxoff_res 0
[ 35108.592366] haxm_error: vcpu has panicked, id:0
[ 35108.592366] haxm_error: log_host_cr4_vmxe: 0
[ 35108.592366] haxm_error: log_host_cr4 0
[ 35108.592366] haxm_error: log_vmxon_res 0
[ 35108.592366] haxm_error: log_vmxon_addr 10f022000
[ 35108.592366] haxm_error: log_vmxon_err_type1 0
[ 35108.592366] haxm_error: log_vmxon_err_type2 0
[ 35108.592366] haxm_error: log_vmxon_err_type3 0
[ 35108.592366] haxm_error: log_vmclear_err 0
[ 35108.592366] haxm_error: log_vmptrld_err 0
[ 35108.592366] haxm_error: log_vmoff_no 0
[ 35108.592366] haxm_error: log_vmxoff_res 0
[ 35108.592366] haxm_error: vcpu has panicked, id:0
[ 35108.592366] haxm_error: log_host_cr4_vmxe: 0
[ 35108.592366] haxm_error: log_host_cr4 0
[ 35108.592366] haxm_error: log_vmxon_res 0
[ 35108.592366] haxm_error: log_vmxon_addr 10f022000
[ 35108.592366] haxm_error: log_vmxon_err_type1 0
[ 35108.592366] haxm_error: log_vmxon_err_type2 0
[ 35108.592366] haxm_error: log_vmxon_err_type3 0
[ 35108.592366] haxm_error: log_vmclear_err 0
[ 35108.592366] haxm_error: log_vmptrld_err 0
[ 35108.592366] haxm_error: log_vmoff_no 0
[ 35108.592366] haxm_error: log_vmxoff_res 0
[ 35108.592366] haxm_error: 
[ 35108.592366] ...........hax_teardown_vm
~~~

Android Emulator or QEMU log: 

Screenshots: n/a

**Additional context**

None

**Comment by raphaelning** [comment] 2019-02-15 02:27
Thanks for the report.

In this case I think the root cause is pretty obvious from the HAXM log: the guest tries to execute the `REP CMPSB` (`0xf3 0xa6`) instruction to perform MMIO, but HAXM's x86 emulator (contributed by @AlexAltea) has left the `CMPS` instructions unimplemented. This one should be straightforward to fix.

**Comment by krytarowski** [comment] 2019-02-15 02:28
`F3 A6 | REPE CMPS m8, m8 | Find nonmatching bytes in ES:[(E)DI] and DS:[(E)SI].`

**Comment by raphaelning** [comment] 2019-02-15 02:30
@krytarowski That's right.

@AlexAltea Do you have time to work on this? :-)

**Comment by AlexAltea** [comment] 2019-02-15 08:20
@raphaelning Sure, I'll allocate time on the weekend for this issue!

**Comment by krytarowski** [comment] 2019-02-17 07:12
@ensra does #176 fix the issue for you?

**Comment by ensra** [comment] 2019-02-17 09:50
@krytarowski yes, it gets further but still doesn't finish booting.

![pnp-nodes](https://user-images.githubusercontent.com/29542929/52911271-5d681c80-3299-11e9-89a8-dccee77faa87.png)

I see a comment relating to this on the [QNX wiki](https://community.qnx.com/sf/wiki/do/viewPage/projects.qemu/wiki/NeutrinoAsGuestInQEMU):

"You'll notice warnings on startup about no P & P BIOS and pci-servers. This can be easily fixed for future boots by making a new .boot file. From a terminal, change working directories to /usr/qnx632/target/qnx6/x86/boot/build and edit the file "qnxbasedma.build". In the script file, we have to start pci-bios before diskboot. The new script section should look like:"

but it seems it should at least boot to the installer.

**Comment by krytarowski** [comment] 2019-02-17 09:59
Does it boot without HAXM? It might be some bios incompatibility from qemu.

**Comment by HaHoYou** [comment] 2019-02-19 08:49
Which iso do you use? which link in http://www.qnx.com/download/ ? I tried 'QNX OS for Safety' , but it needs Product Serial and password to download. Is it not free to download?

**Comment by maronz** [comment] 2019-02-19 23:57
Hmm, I thought the 'Steps to reproduce the behavior:' mentioned 'qnx-6.5.0-x86-201007091524.iso'

So, using a [search](http://lmgtfy.com/?q=qnx-6.5.0-x86-201007091524.iso) one can find an [ISO file](http://fusion.qnx.com/7/23647/qnxsdp-6.5.0-x86-201007091524-nto.iso) with almost exactly that very file name.

In fact, to demonstrate the reported issue, I don't believe one needs the whole 319 MBytes ISO file, as the issue already occurs when booting the (embedded) floppy image. This 2.8 MBytes floppy image could be directly downloaded via:
`curl -r 63488-3012607 -o QNX-6.5.vfd http://fusion.qnx.com/7/23647/qnxsdp-6.5.0-x86-201007091524-nto.iso`
In this case the 'steps to reproduce' would boil down to:
`qemu -snapshot -fda QNX-6.5.vfd -accel hax`

Please note, when using the floppy one runs into the problem that QNX can't find a "file system for mounting". But that is to be expected and the reported crash should have already occurred beforehand. Furthermore, as QNX is famous to run on small systems one certainly does not need 1.5 GBytes of RAM. In my testing with the floppy image using `-m 8` (i.e. allocating 8 MBytes of RAM) seemed to be sufficient.

And BTW, I managed to reproduce the reported issue on a Linux Mint v19.1 x86 host, with QEMU v3.1,  using HAXM master (i.e. 3bdfd1a). I then re-ran the test with 9b30d32, and in this test the issue seemed to have disappeared. But, when I then attempted to re-run the test with 3ee3b48 it did not even appear to boot to the 'SeaBIOS' ROM, so that commit seems to contain a very serious flaw.

**Comment by raphaelning** [comment] 2019-02-20 10:01
@maronz Thanks for the very detailed steps! 3ee3b48 is indeed buggy, and I've updated that PR with 23ca2a0.

**Comment by HaHoYou** [comment] 2019-03-05 03:11
Shall we close this? My trying stopped at the license requirement. yours should be good.

**Closed** 2019-04-03 07:30 UTC
Labels: enhancement
