### ISSUE TITLE
Cannot boot from virtio or AHCI?

### ISSUE THREAD

**Issue by mifritscher** [intel/haxm#34] opened 2018-03-18 09:53 UTC
While being able to access virtio devices while the system is running, it appears that it cannot boot from interfaces other than the default? It seems that the bios can't see the devices.

**Comment by raphaelning** [comment] 2018-03-19 09:36
Could you provide repro steps? I assume you get the expected outcome when you remove `-accel hax` (or `-enable-hax`) from the QEMU command line.

**Comment by mifritscher** [comment] 2018-03-19 11:48
I used a standard mini ubuntu installation (as created in #31), and then tried to start it 

qemu-system-x86_64.exe -m 1024 -drive file=temp.vmdk,if=virtio -vga std -netdev tap,id=hostonly,ifname=tap0 -netdev user,id=natted,hostfwd=tcp::1194-:1194,net=192.168.76.0/24,dhcpstart=192.168.76.164,restrict=n,host=192.168.76.2 -device virtio-net,netdev=natted,mac=00:50:56:00:08:00 -device virtio-net,netdev=hostonly,mac=00:50:56:00:03:00 -nodefaults -accel hax


if I kill ",if=virtio" _or_ "-accel hax" it works - so yes, without hax it works.

**Comment by raphaelning** [comment] 2018-03-20 09:16
Thanks, I've asked a colleague to try this scenario.

We already have test cases that make use of QEMU's virtio block device, such as Android Emulator. But I guess the difference is that they also include the `-kernel` option, so they don't boot directly from disk.

**Comment by raphaelning** [comment] 2018-04-13 09:54
We have reproduced this issue - when booting directly from a virtio drive under HAXM we always get "No bootable device" from SeaBIOS in the end. We just haven't had time to look into it yet.

**Comment by raphaelning** [comment] 2018-08-16 04:31
This issue seems to have been fixed in HAXM 7.3.0. We've tested the following guests, all of which can now boot from a virtio disk drive:

* Debian Wheezy amd64 Standard
* Debian Wheezy amd64 Desktop
* Ubuntu 16.04 Desktop

E.g. this is my QEMU command line for the first test:

`qemu-system-x86_64.exe -m 1024 -vga virtio -drive index=0,media=disk,if=virtio,file=X:\path\to\debian_wheezy_amd64_standard.qcow2 -accel hax`

We haven't tested the Ubuntu 16.04 Mini guest for which the issue was first reported, but since the Desktop edition works, I believe the original issue is also fixed.

We did try Ubuntu 18.04 Mini, which fails to boot on HAXM 7.3.0 but works on the latest HAXM build. I believe that's due to a separate bug (#39), which is fixed in the master branch but not in 7.3.0.

**Comment by raphaelning** [comment] 2018-08-16 04:37
BTW, AHCI also works:

`qemu-system-x86_64.exe -m 1024 -vga virtio -drive index=0,media=disk,if=none,id=mydisk,file=X:\path\to\debian_wheezy_amd64_standard.qcow2 -device ich9-ahci,id=ahci -device ide-drive,drive=mydisk,bus=ahci.0 -accel hax`

**Closed** 2018-11-20 07:16 UTC
Labels: bug
