### ISSUE TITLE
Haxm BSOD

### ISSUE THREAD

**Issue by bp2000** [intel/haxm#157] opened 2019-01-24 12:46 UTC
Summary: 
IntelHaxm.sys throws a System Services Exception BSOD when trying to run the android emulator from android studio.

**Host Environment**

* HAXM version: 7.3.2
* Host OS version: Windows 7 Pro (64-bit)
* Host OS architecture: x86\64
* Host CPU model: Intel Core2 Quad Q9550 @ 2.83GHz
* Host RAM size: 4 GB
* Host computer model: Dell XPS420

**Diagnostic Information**

Host crash dump: [012219-31122-01.zip](https://github.com/intel/haxm/files/2791708/012219-31122-01.zip)

HAXM log: Only haxm entry "haxm_warning:INVEPT was not called due to missing host support (ept_capabilities=0x0)"

**Comment by raphaelning** [comment] 2019-01-25 10:51
Thanks for the report! This should be a duplicate of #147 and #101. It has been fixed, but please downgrade to HAXM 7.2.0 for now, and wait for the HAXM 7.4.0 release.

**Closed** 2021-01-25 02:35 UTC
Labels: duplicate
