### ISSUE TITLE
HAXM 7.3.2 breaks Hypervisor.framework inc. after uninstallation

### ISSUE THREAD

**Issue by delfer** [intel/haxm#112] opened 2018-10-21 10:43 UTC
# Enviroment
- MacBook Pro 2018 MR932
- macOS 10.14 Mojave
- qemu 3.0.0 from Homebrew
- HAXM 7.3.2
- VM image https://download.osimg.ru/arch.qcow2.xz
# Steps
1. Install HAXM `sudo ./HAXM\ installation`
2. Uninstall HAXM `sudo /Library/Extensions/intelhaxm.kext/Contents/Resources/uninstall.sh`
# Was
1 core - `qemu-system-x86_64 -accel hvf -cpu host -smp 1 -m 96 -hda arch.qcow2` - **OK**
2+ core - `qemu-system-x86_64 -accel hvf -cpu host -smp 2 -m 96 -hda arch.qcow2` - **OK**
# Became
1 core - `qemu-system-x86_64 -accel hvf -cpu host -smp 1 -m 96 -hda arch.qcow2` - **OK**
2+ core - `qemu-system-x86_64 -accel hvf -cpu host -smp 2 -m 96 -hda arch.qcow2` - **FAIL**
## Option 1 (less cores/ram)
Hangs on `Loading initial ramdisk ...` with 100% CPU usage
<img width="897" alt="default" src="https://user-images.githubusercontent.com/3233181/47265776-971c5700-d535-11e8-87e6-2e819bf25a77.png">
<img width="912" alt="default" src="https://user-images.githubusercontent.com/3233181/47265769-84098700-d535-11e8-98ab-e86a6d849ece.png">
No errors in console
## Option 2 (more cores/ram)
Black screen.
Errors in console:
```
f5e05: decode_sldtgroup: 0
Unimplemented handler (f5e05) for 107 (f 0)
f5e0f: decode_sldtgroup: 4
Unimplemented handler (f5e0f) for 111 (f 0)
```
<img width="888" alt="default" src="https://user-images.githubusercontent.com/3233181/47265829-64269300-d536-11e8-891c-e806487cf194.png">
<img width="544" alt="default" src="https://user-images.githubusercontent.com/3233181/47265815-3b060280-d536-11e8-91d0-1f8ffa5d9ea6.png">
<img width="752" alt="default" src="https://user-images.githubusercontent.com/3233181/47265814-2de91380-d536-11e8-8839-7d589e8466dd.png">

[crash.log](https://github.com/intel/haxm/files/2500815/crash.log)

# Steps to repair
- Shutdown/reboot (+ force)  - **no effect**
- Install+uninstall with `sudo ./HAXM\ installation -u`  - **no effect**
- Install+uninstall with `sudo ./silent_install.sh -u`  - **no effect**
- Reinstall macOS with data save  - **no effect**
- Fresh install macOS - **no effect**
- Reset NVRAM + SMC - **no effect**

**Comment by raphaelning** [comment] 2018-10-22 10:49
Thanks for the detailed report. I haven't spotted anything harmful in `uninstall.sh`, and I have no idea how it could possibly interfere with running QEMU with `-accel hvf` and `-smp` >=2. The most shocking fact is this:

> Fresh install macOS - no effect

I'm sorry to hear that, but are you saying that after a fresh install of macOS and QEMU, without even installing HAXM again, you still can't launch a multi-core QEMU guest using HVF? Does this happen to `arch.qcow2` only, or to any guest?

**Comment by delfer** [comment] 2018-10-22 11:40
@raphaelning I've also tried reset NVRAM + SMC - no change.
Problem appears also without any guest (just internal SeaBIOS):
```
# qemu-system-x86_64 -accel hvf -cpu host -smp 4 -m 1024
f5e05: decode_sldtgroup: 0
Unimplemented handler (f5e05) for 107 (f 0)
f5e0f: decode_sldtgroup: 4
Unimplemented handler (f5e0f) for 111 (f 0)
f5ef2: decode_sldtgroup: 0
Unimplemented handler (f5ef2) for 107 (f 0)
qemu-system-x86_64: 100000001: unhandled exit 80000021
qemu-system-x86_64: 100000001: unhandled exit 80000021
qemu-system-x86_64: Error: HV_ERROR
[1]    625 abort      qemu-system-x86_64 -accel hvf -cpu host -smp 4 -m 1024
```

**Comment by delfer** [comment] 2018-10-22 13:12
@billtlee can you please check `qemu-system-x86_64 -accel hvf -cpu host -smp 4 -m 1024` on you mac? Thank you!

**Comment by delfer** [comment] 2018-10-22 15:19
I've also checked VMware fusion and mist64/xhyve - they works stable and fast.

**Comment by raphaelning** [comment] 2018-10-23 06:58
I looked up in the QEMU codebase a few error messages you quoted, and they all come from the HVF accelerator module. For example:

```
qemu-system-x86_64: 100000001: unhandled exit 80000021
qemu-system-x86_64: 100000001: unhandled exit 80000021
```

is from `hvf_vcpu_exec()` (`target/i386/hvf/hvf.c`). Here, `80000021` is the VMCS Exit Reason in hex, and means "VM-entry failure due to invalid guest state" according to Intel SDM Vol. 3D Table C-1. But I don't really have time to dig further. You may want to ask the developer of the HVF accelerator to look into this issue on the qemu-devel mailing list.

Meanwhile, we'll try to reproduce the issue on our side and see if it's indeed caused by the HAXM uninstaller.

**Comment by wcwang** [comment] 2018-10-23 10:39
I have verified your issue on my MacBook Pro. The environments are exactly same as what you mentioned except MacBook Pro model. Without uninstallation of HAXM v7.3.2, the issue can be reproduced and the phenomena are hanging on loading initial RAM disk with 100% CPU usage. The results are as below.

$ qemu-system-x86_64 -accel hvf -cpu host -smp 1 -m 96 -hda arch.qcow2 - OK
$ qemu-system-x86_64 -accel hvf -cpu host -smp 2 -m 96 -hda arch.qcow2 - FAILED

Therefore, this issue seems to have no relationship with HAXM uninstallation operation.

**Comment by delfer** [comment] 2018-10-23 11:06
@wcwang thank you for verification!
That means, HAXM breaks Hypervisor.framework in fact and forever and uninstallation do not fix it.

**Comment by raphaelning** [comment] 2018-10-24 02:28
> That means, HAXM breaks Hypervisor.framework in fact and forever and uninstallation do not fix it.

We cannot rule out this possibility, but in order to prove it, we would need to run the HVF SMP test on a  Mac (macOS Mojave) where HAXM has never been installed. We don't have such a Mac though. Do you have one?

Meanwhile, please report this issue to _qemu-devel_ / the author of the HVF accelerator module.

**Comment by raphaelning** [comment] 2018-10-24 02:30
BTW, xhyve is also based on Hypervisor.framework, and you said it works fine. So at least it's not the entire Hypervisor.framework that is "broken," but only the QEMU HVF accelerator.

**Comment by HaHoYou** [comment] 2018-10-24 08:11
Does this fail every time? Or is there any probability number?

**Comment by raphaelning** [comment] 2018-10-24 09:35
@delfer It seems this issue only happens on recent Mac hardware. We have tried to reproduce it on 3 different MBPs from 2014, 2015 and 2017. All of them have upgraded to macOS Mojave, and have or used to have HAXM installed. Only the 2017 MBP (CPU: Intel Core i5-7267U) reproduced the issue.

**Comment by wayne-ma** [comment] 2018-11-20 06:52
Hi @delfer, we just got a new Mac and verified this issue without any HAXM installation/uninstalltion operations. We tested the hvf with different Symmetric Multi-Processors(SMP) options, you can refer to below test result,
Test Env: MacBookPro2018 A1990, i7-8850H, MacOS 10.14, not install HAXM, qemu 3.0.0.

$qemu-system-x86_64 -accel hvf -cpu host -smp 1 -m 96 -hda arch.qcow2 -- Pass 10/10
$qemu-system-x86_64 -accel hvf -cpu host -smp 2 -m 96 -hda arch.qcow2 -- Pass 4/10, Failed 6/10
$qemu-system-x86_64 -accel hvf -cpu host -smp 4 -m 96 -hda arch.qcow2 -- Pass 1/10, Failed 9/10
$qemu-system-x86_64 -accel hvf -cpu host -smp 8 -m 96 -hda arch.qcow2 -- Failed 10/10

As the issue could be reproduced with the such a clean Mac OS ,we can see that it is not related to HAXM but maybe it is related to HVF /SMP. So we close this issue here from HAXM side.

**Closed** 2018-11-20 07:01 UTC
Labels: macos

**Comment by heiher** [comment] 2019-01-24 10:08
The issue was fixed by this patch https://github.com/heiher/qemu/commit/07ebf80b5390610150d17b095d3e9c4eb3de5b74
