### ISSUE TITLE
Windows 10 guest gets stuck on the kernel boot sequence and crashes after a few minutes.

### ISSUE THREAD

**Issue by Mario3264** [intel/haxm#180] opened 2019-02-20 00:22 UTC
**Describe the Bug**

Summary: Almost like issue #118, except it does not crash the host kernel. The summary from it is that the Windows 10 guest gets stuck on the kernel boot sequence, but instead of the host kernel crashing, the guest kernel crashes.

**Host Environment**

* HAXM version: 7.4.1

* Host OS version: Windows 10 Pro Insider Preview (Build 18336)

* Host OS architecture: x86\_64

* Host CPU model: Intel Core i3-4160

* Host RAM size: 8 GB

* (Optional) Host computer model: Dell Inspiron 3847

**Guest Environment**

* Android Emulator or QEMU version: QEMU 3.1.50.0

* Guest OS version: Windows 10 Pro Insider Preview (Build 18334)

* Guest OS architecture: x86\_64

**To Reproduce**

1. Console Command that I ran: "qemu-system-x86_64 -accel hax -drive driver=qcow2,file=win10.qcow2,if=virtio -m 2048 -net nic,model=virtio -net user -cdrom ${WINIMG} -drive file=${VIRTIMG},index=3,media=cdrom -rtc base=localtime,clock=host -smp cores=1 -usb -device usb-tablet -net user,smb=$HOME"
2. Stuck on kernel boot sequence.
3. Eventual guest crash.

**Expected Behavior**

Expectation: Expected it to install precisely how it would install on an actual computer or a normal virtual machine.

**Reproducibility**

**Diagnostic Information**

Host crash dump: None.

HAXM log: [dbgview.log](https://github.com/intel/haxm/files/2882481/dbgview.log)

Android Emulator or QEMU log: 
```
HAX is working and emulator runs in fast virt mode.
VCPU shutdown request
VCPU shutdown request
```

Screenshots: ![image](https://user-images.githubusercontent.com/16366524/53055211-b54e8100-345b-11e9-9421-5598e6c252fc.png)

**Additional context**

None

**Comment by raphaelning** [comment] 2019-02-20 10:29
Thanks for the detailed report. I've already said in https://github.com/intel/haxm/issues/118#issuecomment-446912316 that in order to support 64-bit Windows guests, we need to implement CR8 virtualization properly. The first lines in your HAXM log just give proof to that point:

```
00000358	192.59008789	haxm_warning:Ignored guest CR8 write, val=0x0	
00000359	192.59025574	haxm_warning:Ignored unsupported CR8 read, returning 0	
...
```

So I'll close this issue as a duplicate of #118. But all the information you have provided here is very helpful, and will continue to be available as an update to #118.

**Closed by raphaelning** 2019-02-20 10:29 UTC
Labels: duplicate
