### ISSUE TITLE
disabled Hyper -v still getting error intel x64 6200U-i5

### ISSUE THREAD

**Issue by pavan2sunny** [intel/haxm#210] opened 2019-06-03 10:07 UTC
HAXM installation failed. To install HAXM follow the instructions found at: https://software.intel.com/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-windows
Installer log is located at C:\Users\kumar\AppData\Local\Temp\haxm_log3.txt
Installer log contents:
i used hyper-v before but i disabled it in windows features but still im not able to install haxm 
virtualisation -enabled

**Comment by coxuintel** [comment] 2019-06-04 04:27
Would you share more details about the failure? In addition to the installation log, please help dump result of below commands from PowerShell:
1. systeminfo.exe
2. Get-WmiObject -query "select * from Win32_OptionalFeature

**Comment by DIBYASAMBIT** [comment] 2019-06-04 15:18
[haxm_log4.txt](https://github.com/intel/haxm/files/3253168/haxm_log4.txt)
This the problem plzzz solve

**Comment by coxuintel** [comment] 2019-06-05 00:19
@DIBYASAMBIT The log you attached only states that VT-x is disabled or Hyper-V is enabled, however that's only the direct reason that HAXM can't be installed or run, not the root cause we are looking for. 
Would you mind dump more information, as I mentioned above using systeminfo and PowerShell commands, that may be helpful?
Recently another community user report that on latest Windows 10 1903 HAXM can't be installed with the similar log, and we found that that's due to Windows Sandbox is installed. Would you also check if it's the same case in you case?

**Comment by HaHoYou** [comment] 2019-06-05 06:34
Check the BIOS VT setting:
1. secondary click on the taskbar
2. Task Manager
3. Performance
4. CPU. 
5. In the right bottom, it should be virtualization enabled. 

Check other settings: 
Run command: 
bcdedit /v
sc query intelhaxm
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\CredentialGuard" /s
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity" /s
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard" /s
Also you could check by dgreadiness, E.G.:
powershell dgreadiness_v3.6\DG_Readiness_Tool_v3.6.ps1  -Ready

**Comment by yukiokun057** [comment] 2019-10-07 05:55
If you already turned off Hyper-V in 'Windows Features' and checked BIOS VT setting, but still has this issue. 
Run command: 
bcdedit /v
And check 'hypervisorlaunchtype' property, it could be set 'Auto'.
Run command:
bcdedit /Set hypervisorlaunchtype Off
It will prevent Hyper-V feature launch on booting

**Comment by DIBYASAMBIT** [comment] 2019-10-07 14:38
@coxuintel yeah go to windows defender settings and disable core protection 
![Annotation 2019-10-07 200707](https://user-images.githubusercontent.com/41297760/66321395-1b7e0a80-e93e-11e9-86e0-eb9dd3bd1af6.png)  and disable 
![Annotation 2019-10-07 200810](https://user-images.githubusercontent.com/41297760/66321467-3cdef680-e93e-11e9-830b-20c02b3207e4.png) memory integrity restart and try to install it works

**Comment by silverfrost** [comment] 2019-10-11 10:50
I had the issue. I had 'Windows Sandbox' installed. I removed Windows Sandbox and still had the issue.

Running:
`bcdedit /v `

Does not show an entry for _hypervisorlaunchtype_. However, adding one with:

`bcdedit /Set hypervisorlaunchtype Off`

and rebooting allowed me to install HAXM

**Comment by HaHoYou** [comment] 2019-10-14 06:32
Good to know you all worked. Then I would close this issue.

**Closed by HaHoYou** 2019-10-14 06:32 UTC
